# Generated by Django 5.2.8 on 2025-11-18 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homenagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('dataNascimento', models.DateField()),
                ('dataPlantio', models.DateField()),
                ('especie', models.CharField(max_length=100)),
                ('foto', models.ImageField(upload_to='uploads/')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Homenagens',
            },
        ),
    ]
