# Generated by Django 5.2.8 on 2025-11-18 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homenagens_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_popular', models.CharField(max_length=100, unique=True)),
                ('nome_cientifico', models.CharField(max_length=255, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Espécie de Árvore',
                'verbose_name_plural': 'Espécies de Árvores',
                'db_table': 'Especies',
            },
        ),
        migrations.AlterField(
            model_name='homenagem',
            name='especie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='homenagens', to='homenagens_api.especie'),
        ),
    ]
