# Generated by Django 5.2.8 on 2025-11-18 11:45

import homenagens_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homenagens_api', '0002_especie_alter_homenagem_especie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homenagem',
            name='codigo',
            field=models.CharField(blank=True, default=homenagens_api.models.generate_unique_code, max_length=50, unique=True),
        ),
    ]
